const BREAKPOINT_TABLET = 768
const BREAKPOINT_DESKTOP = 1024

const BREAKPOINTS = {
  mobile: 0,
  tablet: BREAKPOINT_TABLET,
  desktop: BREAKPOINT_DESKTOP,
}

export {
  BREAKPOINT_DESKTOP,
  BREAKPOINT_TABLET,
  BREAKPOINTS,
}
